# Generated by Django 5.0.2 on 2025-01-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("sum", "Сумма чисел"),
                            ("countdown", "Обратный отсчет"),
                        ],
                        max_length=20,
                        verbose_name="Тип задачи",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="Входные данные")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "FAILURE"),
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("RETRY", "RETRY"),
                            ("REVOKED", "REVOKED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="Результат"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
